### ISSUE TITLE
Admin Controllers User algo cambio¿?

### ISSUE THREAD

**Issue by facundoruiz** [waifung0207/ci_bootstrap_3#13]
En este controlador es el crud de users en la
 linea 13 hace referencia a una relacion "role" (el cual es un campo de los admin_users), pero creo que debería ser a group_id de la tabla user_groups.
tenia entendido que este controlador seria para los user del front..

Antes 
```php
$crud->columns('group_id', 'email', 'first_name', 'last_name', 'active', 'created_at');
$crud->set_relation('group_id', 'user_groups', 'name');
```
Ahora 
```php
$crud->columns('role', 'email', 'first_name', 'last_name', 'active', 'created_at');

```

**Comment by waifung0207** [comment]
Sorry there was some data inconsistency in previous version; I am still working on this project and hopefully can keep a more stable data structure in near future. 

In latest update I have made changes include:
* **user** table now contains only **role** enum field (instead of group_id)
* **user_groups** table is removed to keep the structure more simple
* Admin Panel is updated according to latest data structure

Thanks for reporting the issue.
