### ISSUE TITLE
Few words about the last commits

### ISSUE THREAD

**Issue by buoncri** [waifung0207/ci_bootstrap_3#15]
First of oll ... thank you for this very very nice piece of software :clap:, and soon after some reporting:

- GroceryCrud now have not problems whith ckeditor ... but I think it remain disabled for me :+1: 
- After some modifications on the image crud example ad some other work whith a custom photo-crud i notice that is impossible to append a value after the url  - base/class/method/value - becouse it returns an arror that make impossible to pass a value to the function. :-1: 
```
A Database Error Occurred
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '1' ORDER BY `pos`' at line 3

SELECT * FROM `cover_photos` WHERE = '1' ORDER BY `pos`

Filename: modules/admin/libraries/Image_crud.php
Line Number: 363
```
It seems like there be a where clause ...
- Blog example: the gcrud /ci_bootstrap_3/admin/blog/post/edit/1 seems to duplicate the tags section. If i add tag1, on the next read/edit access to the record i can see two "tag1" bootstrap icon and so for tag2 and 3. :umbrella: 

Thank's again ;-)

**Comment by waifung0207** [comment]
Thanks for the feedback :)

* In latest update, I have reverted the default editor back to **ckeditor** for Grocery CRUD, which I agree it is better to leave it as a choice whether the developer needs to change it or not
* I want more details about this issue, since I added a member variable **$where** into **MY_Model.php**, which may leads to this problem. Did you make amendment on **Cover_photo_model.php** and can you share the code for me to investigate?
* Do you mean if more tags with same naming (e.g. two "tag1" records in database) will show duplicated tags for selection? If I didn't understand wrongly, that is expected result since two "tag1" have different id therefore should be different entries. Perhaps you can consider setting the **title** field of **blog_tags** table as unique in MySQL database (you may also need to use [unique_fields](http://www.grocerycrud.com/documentation/options_functions/unique_fields) function from Grocery CRUD) to avoid duplicated tags.

**Comment by buoncri** [comment]
1) ok
2) ... I will investigate more deeply 
3) yes, duplicate tags (in view).
