### ISSUE TITLE
different menu for user levels

### ISSUE THREAD

**Issue by Qnatz** [waifung0207/ci_bootstrap_3#17]
Hey nice start-up, am trying to give user levels different menus.... like the admin can access every thing(i added the admin users in the sidemenu) but the staff should not see the admin users link. you also disabled it in the script. i thought of if ($user->role=='admin') in site.php but am getting a non-object error coz $user is not defined. In sidemenu.php i see $menu which i think is an array coming from site.php, is there a way to access this array maybe i can hide the  desired link before its echoed. u have any solution for this...

**Comment by waifung0207** [comment]
Thanks for raising the issue, Admin Panel's role permission is definitely one of my desired features so I am figuring out a better solution on this. 

Please have a look on the current version, and you will find this file with some role handling:
- /applications/modules/admin/config/site.php
From the 'menu' array inside the file, I have separated 'admin' role 'staff' role to display different items on the sidemenu. If you require more complex logic, you may consider changing the codes directly from /applications/modules/admin/views/_partials/sidemenu.php

If you want to limit user access to certain controllers, you will need to use the verify_role() function from Admin_Controller, and redirect to login page in case the user is not authorized.

**Comment by genebryle** [comment]
/applications/modules/admin/config/site.php From the 'menu' array inside the file, I have separated 'admin' role 'staff' role to display different items on the sidemenu. 

Hi, I also got the same problem, I'm a bit confused all permissions were already set but still staff and manager user types are still able to see the admin links. Can you please us. 

Btw, I am new to your repo and amazed by how its done. Great work!

**Comment by jvila** [comment]
Hi, I have a similar question.
I've added a "company" field to the user table and then I'd like to add a menú access to the edit company screeen like 

		'company' => array(
			'name'		=> 'Companies',
			'url'		=> 'company',
			'icon'		=> 'ion ion-load-b',
			'children'  => array(
				'Company list' => 'explotacio/empresa',
                                 'Edit User's company'        => 'explotacio/empresa/edit/'.$user->company,

is it possible to access logged in user information on the site.php file? I'm getting a non-object error. user not found

Thanks

**Comment by waifung0207** [comment]
Hi all, in one of the latest commits (dd25bcce82414b4982243fa02f2051b4e8b7f6ba), the repo have included a new feature which can limit page access and sidemenu items for different roles.

Please take a look at **/application/modules/admin/config/site.php**, you will find a "page_auth" array to state which pages can be accessed by which groups of users.

Regarding the question from @jvila, since the site.php config file is loaded before any other logic from controller / model (e.g. database retrieval), it is expected to receive non-object error there. For my own practices, normally I will add some code manually into MY_Controller (or Admin_Controller) to manipulate the $this->mMenu variable, so it can include entries which involved data from database just like what you did.

Please let me know if you have further questions. Thanks.
