### ISSUE TITLE
About the implementation of hmvc

### ISSUE THREAD

**Issue by buoncri** [waifung0207/ci_bootstrap_3#18]
Hi 
After some time spent on using this "codeigniter+ distro" :-D i have a little question about hmvc implementation in ci_bootstrap_3.

As i sow, the MY_model extend CI_model and not MX_model. There can a lot of reason to have completly separated modules but extending MX_controller can be a way to implement widgets with some simple modules template.

Have a nice day ;-)

**Comment by waifung0207** [comment]
Sorry I'm a little bit unclear about MX_model since I cannot find it from the HMVC repository, but I agree I can use modules extending MX_controller to provide widgets - I will further consider it. 

Currently, MY_Model should extend from Base_Model (which is renamed from [jamierumbelow's MX_Model](http://github.com/jamierumbelow/codeigniter-base-model)), and it provides lots of features which help with database operations. I just noticed my README is not up-to-update and didn't mention it, will add it back soon.

Thanks!

**Comment by buoncri** [comment]
Talking about the MY_model, i'd like to report https://github.com/avenirer/CodeIgniter-MY_Model. Based on Jamie Rumbelow's Base Model with some other function.

Bye and have a good week end :-D
