### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by boloindia** [waifung0207/ci_bootstrap_3#43]
This is indeed a wonderful work done. Thank you for that. But the Role based implementation is not done all correctly. Though the configuration is done in site.php but when I login as staff or when I login as admin, that makes no difference in the Side Menu. Also, if I type the URL in the address bar directly, there are no restrictions. 
In case, these two implementation are done, this will really be great. :)

**Comment by boloindia** [comment]
@waifung0207 any plans to implement Role Based Access for Admin Users?

**Comment by waifung0207** [comment]
This is a good call because I am also preparing to add this feature into the repo. Currently you can still use **verify_login()** and **verify_auth()** functions from MY_Controller to check with user login.

Please stay tuned and I will implement the role handling from site.php in near future. Thanks for the issue.

**Comment by waifung0207** [comment]
In latest commit (dd25bcce82414b4982243fa02f2051b4e8b7f6ba), I have implemented the feature aforementioned.

Now you will see from site.php, there is a **page_auth** array to define page restrictions for different groups of login users, which will also affect the items appearing on sidemenu. In the mean time, "groups" array under menu is removed since it is not necessary any more; and the "groups" array of useful_links is now renamed to "auth" due to consistency.

You may try it out and see if there is any problems.

**Comment by boloindia** [comment]
sure Thanks @waifung0207 :) I'll check it out and revert to you

**Comment by cansanet** [comment]
@waifung0207 What is the correct way of hiding login and signup buttons from logged in user. And also show logged in user account or profile link.

**Comment by waifung0207** [comment]
@cansanet Yes I will use $this->ion_auth->logged_in() to limit access to pages like Login / Sign Up.
