### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by cansanet** [waifung0207/ci_bootstrap_3#48]
Hi @waifung0207,

You did an awesome work. Congratulations. I have an issue if it is possible.
I have codeigniter membership script which has only one login page for users and admin users.
On my script when you type http://localhost/codeigniter/admin you go nowhere. But if you type this after logged in as admin from common login page, you can access to admin page. This is a very good idea to hide admin panel from public.

Another issue is login with social media. There is a library named hybridauth. Is it possible to add this library to ci_bootstrap_3 if not I will give it a try.

Again thank you very much for this very awesome work.

**Comment by waifung0207** [comment]
Thanks for raising the issue.

I understand the concept of single Login page to hide Admin Panel from public, but currently I use separate tables for Frontend & Admin users (so you will see 8 database tables are created, each modules have 4 tables due to Ion Auth) which I think have better security; in addition I use slightly different setup for Frontend users (login by email) and Admin users (login by username), so I would rather keep the login page apart. But of course you can customize the setup according to your own usage. 

Alternative method to "hide" the Admin Panel may be: just rename the admin module with random number (e.g. admin5252798) which is used in some other tools / frameworks (like PrestaShop as far as I know). 

Social login is not planned to add into the repo yet, but I would keep it in mind and perhaps someday I will consider it. 

Thanks again :)
