### ISSUE TITLE
Change URL address

### ISSUE THREAD

**Issue by danzhu10** [waifung0207/ci_bootstrap_3#59]
How can i change URL address ? my link show like this http://[::1]/adminpanel/. 
Can i change the " http://[::1] " with localhost ?
thanx

**Comment by edos4** [comment]
Follow up on this please. Thanks.

**Comment by waifung0207** [comment]
CodeIgniter had changed the base_url behaviour since v3.0.3 (reference link [here](http://www.codeigniter.com/user_guide/changelog.html#version-3-0-3)) and it is recommended to change it from config file ($config['base_url'] value from /application/config/config.php).

If empty value is set, IP address will be used automatically for different setup (e.g. Linux gives 127.0.0.1, while Mac OS gives [::1] as stated, and will cause errors and lead to assets / scripts not found.

**Comment by edos4** [comment]
@danzhu10 , I've added:
```
$root = "http://".$_SERVER['HTTP_HOST'];
$root .= dirname($_SERVER['SCRIPT_NAME']);
$config['base_url']    = $root;
```
to application/config/config.php and it made me happy.

**Comment by danzhu10** [comment]
Oke thank you all. Problem solve :)
