### ISSUE TITLE
Error en leer config site

### ISSUE THREAD

**Issue by facundoruiz** [waifung0207/ci_bootstrap_3#6]
accedo a http://localhost/ci/account/sign_up
or
example/form_basic
or
example/demo/1

A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '['
Filename: libraries/Form_builder.php
Line Number: 375
and
Line Number: 409 

en general parece ser un problema con la lectura de $this->CI->config->item('recaptcha')['site_key'];
y también tengo el mismo problema  cuando lee $this->CI->config->item('site')['auth'] 

mi info sistema 
PHP Version 5.3.6;
Apache 2.0
Windows7

**Comment by facundoruiz** [comment]
Estuve probando con PHP 5.2 y esta funcionando.

**Comment by buoncri** [comment]
something similar with php 5.3.ecc and 5.6 :-D

**Comment by waifung0207** [comment]
Can you please verify there are values under $config['recaptcha'] inside the file: application/config/form_validation.php ?

I'm wondering if the issue is due to PHP version but if it happens even in v5.6, should have somethings wrong :/ 

Anyway I have pushed a small commit trying to fix the issue, basically just separate the lines like this:
```php
$config = $this->CI->config->item('recaptcha'); 
$site_key = $config['site_key'];
```

Please test again, thank you all.
