### ISSUE TITLE
Undefined variable: message

### ISSUE THREAD

**Issue by lruixiang** [waifung0207/ci_bootstrap_3#60]
Hi, I'm kind of new with this. Managed to get the installation going, was able to access most of the pages except for Login page. It's showing the header and the following as the content.
Any idea why the message variable is not defined from the controller?

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: message

Filename: auth/login.php

Line Number: 4

Backtrace:

File: /home/revest/public_html/application/third_party/ion_auth/views/auth/login.php
Line: 4
Function: _error_handler

**Comment by waifung0207** [comment]
Thanks for reporting the issue.

The problem is due to the view file (auth/login.php) conflict from Ion Auth (/application/third_party/ion_auth/views/) with that from Frontend Website. I have resolved it by changing the folder to "views_sample" in last commit (3456229f307e99ccc7f644a46f2ca6a3d5df6eec) and it should work fine now.

**Comment by lruixiang** [comment]
Thanks waifung. 
If possible, can you walk me through how you manage to catch that conflict?

**Comment by waifung0207** [comment]
I caught the conflict because I saw the file "/home/revest/public_html/application/third_party/ion_auth/views/auth/login.php" is shown in Backtrace, so I wonder whether it overrides the display of my own auth/login.php view. Then it is proved after I did a quick test changing the folder name from Ion Auth.
