### ISSUE TITLE
Login to admin panel and front-end share the same auth 

### ISSUE THREAD

**Issue by cyruspak** [waifung0207/ci_bootstrap_3#64]
After I logged in frontend page by a normal user account with user id 1, when i go to admin page, it auto mapped to admin user id 1. That means i don't need to login admin page and can operate admin functions.

**Comment by waifung0207** [comment]
Yes I just noticed this issue from another developer.

For a quick solution, you may try to add this line to the admin module's site.php:
$config['sess_cookie_name'] = 'ci_session_admin';

So it will override the global one (from /application/config/config.php) and use different sessions.

Please let me know if this can resolve the problem.

**Comment by codestellar** [comment]
Thanks @waifung0207 Why not to add this in the commit? Also I was thinking that menu and access/privileges should come from database. Thanks a lot once again.

**Comment by codestellar** [comment]
@waifung0207 the bug is still there. This time I did:

-Logged in as Webmaster
-Loggedout
-Logged in as member
-Opened Admin panel by typing the URL directly
-The url does not open (The above code has fixed the bug)
-Logged in as webmaster again
-Opened member panel 
-The member panel opens :(

**Comment by waifung0207** [comment]
@codestellar 

Logging in Admin Panel will not logout Frontend user automatically, since two sites are now using different session data, so I believe this is an expected result. It looks fine as long as two websites are using different identities (Frontend users for Frontend Website, Admin users for Admin Panel). 

The reason for not adding the line "$config['sess_cookie_name'] = 'ci_session_admin';" to repo is because of I am working on some rearranging some folder structure (mainly to separate demo pages from main sites for better isolation), please stay tuned.
