### ISSUE TITLE
Can't login or create user

### ISSUE THREAD

**Issue by LonoSpangle** [waifung0207/ci_bootstrap_3#8]
Hello,

nice project. I tried to set this up on my machine, but have a little trouble logging in. 

When I try to login with "admin" as defined in the sql dump it always sais:
```
The Email field must contain a valid email address.
```
As far as I can see in the database there is no column "email"

When I try to register a new user it says:
```
The Email field must contain a unique value.
```

It also looks like there is no access to the database...
Or I just can't find where exactly the db access happens

Anybody having the same issues?

**Comment by buoncri** [comment]
in db i see there are 2 tables for autentication, users and admin_users. Admin is in the second table. Ergo, admin can login only in backend.

**Comment by waifung0207** [comment]
Thanks buoncri for helping on the reply.

Yes there are two tables where "users" is for Frontend users (i.e. for membership system), while "admin_users" is for Admin Panel only, and the latter require username instead of email. 

For Admin Panel, please remember to visit URL like: http://localhost/ci_bootstrap_3/admin/ and login there.
